# .travis.yml
language: node_js

sudo: required

services:
  - docker

node_js:
  - '6'
  - '7'
  - '8'

env:
  - POSTGRESQL_VERSION=9.4 MYSQL_VERSION=5.5
  - POSTGRESQL_VERSION=9.5 MYSQL_VERSION=5.6
  - POSTGRESQL_VERSION=9.6 MYSQL_VERSION=5.7

before_install:
  - sudo service postgresql stop && sudo service postgresql start $POSTGRESQL_VERSION
  - sudo service mysql stop || sudo service mysql-5.6 stop || sudo stop mysql-5.6 || sudo stop mysql || echo "failed to stop mysql"
  - sudo docker pull mysql:$MYSQL_VERSION
  - sudo docker run --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -d mysql:$MYSQL_VERSION
  - sleep 10

before_script:
  - psql -U postgres -c "CREATE USER db_errors SUPERUSER"
  - psql -U postgres -c "CREATE DATABASE db_errors_test"
  - mysql --user=root --password=root -h 127.0.0.1 --protocol=tcp -e "CREATE USER db_errors"
  - mysql --user=root --password=root -h 127.0.0.1 --protocol=tcp -e "GRANT ALL PRIVILEGES ON *.* TO db_errors"
  - mysql --user=root --password=root -h 127.0.0.1 --protocol=tcp -e "CREATE DATABASE db_errors_test"

script:
  - npm run-script test-travis

notifications:
  email: false
